diff -Naur fotoxx-9.1.orig/Makefile fotoxx-9.1/Makefile
--- fotoxx-9.1.orig/Makefile	2009-12-26 16:25:07.526824509 +0200
+++ fotoxx-9.1/Makefile	2009-12-26 16:28:07.053822116 +0200
@@ -5,30 +5,30 @@
 SOURCE = $(PROGRAM)-$(VERSION).cpp
 
 # replace CFLAGS and LFLAGS -O3 with -g for GDB debugging
-CFLAGS = -O3 -Wall -c `pkg-config --cflags gtk+-2.0`
-LFLAGS = -O3 -Wall -rdynamic `pkg-config --libs gtk+-2.0 gthread-2.0`
+CFLAGS = -g -Wall -c `pkg-config --cflags gtk+-2.0`
+LFLAGS = -g -Wall -rdynamic -lfreeimage `pkg-config --libs gtk+-2.0 gthread-2.0`
 
 # use $PREFIX if defined, else assume /usr/local
 ifeq "$(PREFIX)" ""
-	PREFIX = /usr/local
+	PREFIX = /usr
 endif
 
 BINDIR = $(PREFIX)/bin
 DATADIR = $(PREFIX)/share/$(PROGRAM)
 DOCDIR = $(PREFIX)/share/doc/$(PROGRAM)
-DESKTOP = $(DATADIR)/kornelix-$(PROGRAM).desktop
+DESKTOP = $(PREFIX)/share/applications/$(PROGRAM).desktop
 MANDIR = $(PREFIX)/share/man/man1
 
 $(PROGRAM): $(PROGRAM).o zfuncs.o
 	@ ./dependencies.sh
-	@ g++ $(LFLAGS) -lfreeimage -o $(PROGRAM) $(PROGRAM).o zfuncs.o
+	@ $(CXX) $(LDFLAGS) -lfreeimage $(PROGRAM).o zfuncs.o -o $(PROGRAM) $(LFLAGS)
 
 $(PROGRAM).o: $(SOURCE)
-	@ g++ $(CFLAGS) -o $(PROGRAM).o $(SOURCE)		\
+	@ $(CXX) $(CFLAGS) -o $(PROGRAM).o $(SOURCE)        \
 	  -D "DATADIR=\"$(DATADIR)\"" -D "DOCDIR=\"$(DOCDIR)\""
 
 zfuncs.o: zfuncs.cpp
-	@ g++ $(CFLAGS) zfuncs.cpp	\
+	@ $(CXX) $(CFLAGS) zfuncs.cpp   \
 	  -D "DATADIR=\"$(DATADIR)\"" -D "DOCDIR=\"$(DOCDIR)\"" -D "BINDIR=\"$(BINDIR)\""
 
 install: $(PROGRAM)
@@ -42,15 +42,15 @@
 	cp $(PROGRAM) $(DESTDIR)$(BINDIR)
 	cp -R locales/* $(DESTDIR)$(DATADIR)/locales
 	#  install .desktop file (menu entry)
-	@echo "[Desktop Entry]" > $(DESKTOP)
-	@echo "Name=$(PROGRAM)" >> $(DESKTOP)
-	@echo "Categories=Graphics" >> $(DESKTOP)
-	@echo "Type=Application" >> $(DESKTOP)
-	@echo "Terminal=false" >> $(DESKTOP)
-	@echo "Exec=$(BINDIR)/$(PROGRAM)" >> $(DESKTOP)
-	@echo "Icon=$(DATADIR)/icons/$(PROGRAM).png" >> $(DESKTOP)
-	@echo "GenericName=Digital Photo Editor" >> $(DESKTOP)
-	xdg-desktop-menu install $(DESKTOP)
+# 	@echo "[Desktop Entry]" > $(DESKTOP)
+# 	@echo "Name=$(PROGRAM)" >> $(DESKTOP)
+# 	@echo "Categories=Graphics" >> $(DESKTOP)
+# 	@echo "Type=Application" >> $(DESKTOP)
+# 	@echo "Terminal=false" >> $(DESKTOP)
+# 	@echo "Exec=$(BINDIR)/$(PROGRAM)" >> $(DESKTOP)
+# 	@echo "Icon=$(DATADIR)/icons/$(PROGRAM).png" >> $(DESKTOP)
+# 	@echo "GenericName=Digital Photo Editor" >> $(DESKTOP)
+# 	xdg-desktop-menu install $(DESKTOP)
 	#  install man page
 	cp -f doc/$(PROGRAM).man $(PROGRAM).1
 	gzip -f -9 $(PROGRAM).1
