#!/bin/sh
# Needed to make symlinks/shortcuts work.
# the binaries must run with correct working directory
echo "et.x86 0 0 direct" > /proc/asound/card0/pcm0p/oss
cd "/opt/enemy-territory/"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
exec ./et.x86 "$@"

