#!/bin/sh
#
# This starup script will set the correct library path
# and then startup the teamspeak server binary.
#

export LD_LIBRARY_PATH=/usr/share/teamspeak:$LD_LIBRARY_PATH
/usr/share/teamspeak/server_linux $* 
