#!/bin/sh
###
#
# Listen is the legal property of mehdi abaakouk <theli48@gmail.com>
# Copyright (c) 2006 Mehdi Abaakouk
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
###

export LISTEN_LIBRARY_PATH="/usr/lib/listen"
export LISTEN_DATA_PATH="/usr/share/listen"
export LISTEN_VERSION="0.6"

cd $LISTEN_LIBRARY_PATH && MOZILLA_FIVE_HOME=/usr/lib/xulrunner-1.9 exec python -OO listen "$@"
