diff -Naur rlplot.orig/Makefile rlplot/Makefile
--- rlplot.orig/Makefile	2008-05-02 18:48:33.000000000 +0300
+++ rlplot/Makefile	2010-01-29 15:57:08.677251836 +0200
@@ -18,8 +18,8 @@
 #    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #
 #
-CC = g++
-X11LIBS = -lX11 -lm
+CC = $(CXX)
+X11LIBS = -lm
 SRCDIR = ./
 
 #######
@@ -39,12 +39,12 @@
 
 #######
 #######   Declarations for Qt4
-QT4DIR = /usr/lib/qt4
-QT4MOC = /usr/lib/qt4/bin/moc-qt4
+QT4DIR = /usr/qt/4
+QT4MOC = /usr/qt/4/bin/moc
 MOC4FLAGS = "MOCFLAGS=-DQT_VERSION=0x040000"
-QT4CFLAGS = "-I/usr/include/Qt -pipe -O2"
+QT4CFLAGS = "$(CFLAGS) $(LDFLAGS) -I/usr/qt/4/include -I/usr/qt/4/include/Qt -pipe"
 QT4H = QT_Spec.h
-QT4LIBS = "-L$(QT4DIR)/lib -L/usr/X11R6/lib -lQtCore -lQtGui"
+QT4LIBS =  "-L$(QT4DIR)/lib -L/usr/X11R6/lib -lQtCore -lQtGui"
 #
 #   If above declarations don't work for Qt4 try the following ...
 #QT4DIR = /usr/share/qt4
