diff -Naur logisim-2.1.6_orig/Makefile logisim-2.1.6/Makefile
--- Makefile	1970-01-01 02:00:00.000000000 +0200
+++ Makefile	2007-12-12 23:53:47.000000000 +0200
@@ -0,0 +1,29 @@
+JFLAGS =
+JAVAC = /opt/sun-jdk/bin/javac
+
+SUBDIRS = src/com/cburch/hex \
+	src/com/cburch/logisim \
+	src/com/cburch/logisim/analyze/gui \
+	src/com/cburch/logisim/analyze/model \
+	src/com/cburch/logisim/circuit \
+	src/com/cburch/logisim/comp \
+	src/com/cburch/logisim/data \
+	src/com/cburch/logisim/file \
+	src/com/cburch/logisim/gui/hex \
+	src/com/cburch/logisim/gui/log \
+	src/com/cburch/logisim/gui/main \
+	src/com/cburch/logisim/gui/menu \
+	src/com/cburch/logisim/gui/opts \
+	src/com/cburch/logisim/gui/prefs \
+	src/com/cburch/logisim/gui/start \
+	src/com/cburch/logisim/legacy \
+	src/com/cburch/logisim/proj \
+	src/com/cburch/logisim/std \
+	src/com/cburch/logisim/tools \
+	src/com/cburch/logisim/util \
+
+all:
+	@@for file in $(SUBDIRS); do \
+		$(JAVAC) $(JFLAGS) $$file/*.java; \
+		$(RM) $$file/*.java; \
+	done
