#!/bin/bash

MAIN="planeshift"

DATADIR="/usr/share/$MAIN"

TARGET="$HOME/.$MAIN"

TOSYMLINK="art data lang pawseditor texparse ase_2_spr eedit paws_generic psnpcclient psserver updater"

TOCOPY="eedit.cfg pawseditor.cfg psclient.cfg psupdater.cfg npcclient.cfg paws_generic.cfg psserver.cfg vfs.cfg partview.cfg planeshift.cfg pssetup.cfg pssetup psclient"

if [ ! -e "$TARGET" ]; then
        mkdir "$TARGET"
fi
for d in $TOSYMLINK; do
        if [ ! -e "$TARGET/$d" ] ; then
                ln -s "$DATADIR/$d" "$TARGET/$d"
        fi
done
for f in $TOCOPY; do
        if [ ! -e "$TARGET/$f" ] ; then
                cp -R "$DATADIR/$f" "$TARGET/"
        fi
done

cd "$TARGET"

export CEL=/usr/lib/cel

LC_ALL=C ./pssetup "$@"
