diff -Naur K7Z-0.5-orig/Build/Makefile K7Z-0.5/Build/Makefile
--- K7Z-0.5-orig/Build/Makefile	2006-12-09 08:18:31.000000000 +0200
+++ K7Z-0.5/Build/Makefile	2006-12-09 11:40:14.000000000 +0200
@@ -45,8 +45,6 @@
 	chmod -R 775 $(KDEDIR)/share/apps/K7Z/
 	ln -fs $(KDEDIR)/share/apps/K7Z/Source/K7Z.pyw $(KDEDIR)/bin/K7Z.pyw
 	cp -u ../Desktop/Context/Live/* $(KDEDIR)/share/apps/konqueror/servicemenus/
-	rm -f ~$(USER)/.kde/share/apps/konqueror/servicemenus/K7Z*
-	cp ../Desktop/Context/Live/* ~$(USER)/.kde/share/apps/konqueror/servicemenus/
 	mkdir -p $(KDEDIR)/share/applnk/Utilities/File/
 	cp ../Desktop/KMenu/* $(KDEDIR)/share/applnk/Utilities/File/
 	mkdir -p $(KDEDIR)/share/icons/hicolor/32x32/apps/
