#!/bin/bash
#
# Copyright 2007 TUBITAK/UEKAE
# Licensed under the GNU General Public License, version 2.
# See the file http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

rm -rf ~/.config/compiz
rm -f ~/.config/compiz-managerrc
rm -f ~/.config/fusion-icon
rm -f ~/.emerald/settings.ini
rm -f ~/.kde/share/config/compizrc

echo "OK. All configuration files related with compiz-fusion has been deleted."
