diff -Nuar ctemplate-0.8.orig/Makefile.in ctemplate-0.8/Makefile.in
--- ctemplate-0.8.orig/Makefile.in	2007-08-17 23:31:59.000000000 +0300
+++ ctemplate-0.8/Makefile.in	2008-01-06 16:48:32.000000000 +0200
@@ -401,11 +401,9 @@
 	src/google/template_namelist.h.in \
 	src/google/template_from_string.h.in
 
-docdir = $(prefix)/share/doc/$(PACKAGE)-$(VERSION)
-dist_doc_DATA = AUTHORS COPYING ChangeLog INSTALL NEWS README README.windows \
-	doc/designstyle.css doc/index.html \
-	doc/howto.html doc/tips.html doc/example.html \
-	doc/xss_resources.html
+docdir = $(prefix)/share/doc/google-$(PACKAGE)-$(VERSION)
+dist_doc_DATA = AUTHORS COPYING ChangeLog NEWS README  \
+
 
 
 # automake will make different .o files for this library, which is good,
