--- org-Makefile	2001-09-07 10:40:21.000000000 +0300
+++ Makefile	2006-07-27 19:07:56.000000000 +0300
@@ -15,8 +15,8 @@
 LIBS=$(SDL_LIBS) $(MIXERLIB) -lSDL_image
 MIXERLIB=-lSDL_mixer
 
-DATA_PREFIX=/usr/share/tuxmath/
-BIN_PREFIX=/usr/local/bin/
+DATA_PREFIX=/var/tmp/pisi/tuxmath-2001.09.07-0102-1/install/usr/share/tuxmath/
+BIN_PREFIX=/var/tmp/pisi/tuxmath-2001.09.07-0102-1/install/usr/bin/
 
 
 VERSION=2001.09.07
