--- Makefile.orig	2001-09-07 10:40:21.000000000 +0300
+++ Makefile	2006-10-28 00:09:43.000000000 +0300
@@ -16,8 +16,8 @@
 MIXERLIB=-lSDL_mixer
 
 DATA_PREFIX=/usr/share/tuxmath/
-BIN_PREFIX=/usr/local/bin/
-
+BIN_PREFIX=/usr/bin/
+INSTALL_DIR=/var/tmp/pisi/tuxmath-2001.09.07-0102-2/install/
 
 VERSION=2001.09.07
 
@@ -30,14 +30,14 @@
 
 install:
 	@echo "COPYING BINARY TO $(BIN_PREFIX)"
-	cp tuxmath $(BIN_PREFIX)
-	chown root.root $(BIN_PREFIX)/tuxmath
-	chmod a+rx,g-w,o-w $(BIN_PREFIX)/tuxmath
+	cp tuxmath $(INSTALL_DIR)$(BIN_PREFIX)
+	chown root.root $(INSTALL_DIR)$(BIN_PREFIX)/tuxmath
+	chmod a+rx,g-w,o-w $(INSTALL_DIR)$(BIN_PREFIX)/tuxmath
 	@echo "COPYING DATA FILES TO $(DATA_PREFIX)"
-	mkdir -p $(DATA_PREFIX)
-	cp -r data/* $(DATA_PREFIX)
-	chown -R root.root $(DATA_PREFIX)
-	chmod -R a+rX,g-w,o-w $(DATA_PREFIX)
+	mkdir -p $(INSTALL_DIR)$(DATA_PREFIX)
+	cp -r data/* $(INSTALL_DIR)$(DATA_PREFIX)
+	chown -R root.root $(INSTALL_DIR)$(DATA_PREFIX)
+	chmod -R a+rX,g-w,o-w $(INSTALL_DIR)$(DATA_PREFIX)
 
 clean:
 	-rm tuxmath
