diff -Naur fltk-2.0.0-orig/Makefile fltk-2.0.0/Makefile
--- fltk-2.0.0-orig/Makefile	2006-09-07 18:11:45.000000000 +0300
+++ fltk-2.0.0/Makefile	2006-09-07 19:09:13.000000000 +0300
@@ -25,7 +25,7 @@
 
 include makeinclude
 
-DIRS = src $(LOCALIMAGES) images OpenGL fluid glut test
+DIRS = src $(LOCALIMAGES)
 
 all: makeinclude
 	for dir in $(DIRS); do\
