--- Makefile	2004-02-11 06:57:17.000000000 +0200
+++ Makefile-yeni	2006-05-19 20:53:56.000000000 +0300
@@ -11,7 +11,7 @@
 all: bbrun
 
 .c.o:
-	$(CC) -g -c -O2 -Wall $< -o $*.o $(CFLAGS)
+	$(CC) -c  -Wall $< -o $*.o $(CFLAGS)
 
 bbrun: $(OBJS)
 	$(CC) -Wall -g -o bbrun $^ $(LIBDIR) $(LIBS)
