--- Makefile.in.orig	2008-10-08 05:12:53.000000000 +0300
+++ Makefile.in	2008-10-08 05:15:53.000000000 +0300
@@ -139,7 +139,7 @@
 compileall:
 ifneq (x"$(nopycompile)",xYES)
 	for dir in src mpd soundcard; do\
-	  $(PYTHON) -c "import compileall; compileall.compile_dir('$(datadir)/$(PACKAGE)/$$dir')" ;\
+	  $(PYTHON) -c "import compileall; compileall.compile_dir('$(DESTDIR)/$(PACKAGE)/$$dir')" ;\
 	done
 endif
 
