#!/bin/sh
cd "/opt/enemy-territory"
if [ -n "/opt/enemy-territory" ] ; then
	if [ "${LD_LIBRARY_PATH+set}" = "set" ] ; then
		export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/enemy-territory"
	else
		export LD_LIBRARY_PATH="/opt/enemy-territory"
	fi
fi
exec ./et.x86 "$@"
